const posts = [
  {
    id: 0,
    creator: 'Lisa Nuyk',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/lisa1.jpg'),
  },
  {
    id: 1,
    creator: 'Lisa Nuyk',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/lisa2.jpg'),
  },
  {
    id: 2,
    creator: 'Tom Fisk',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/tom1.jpg'),
  },
  {
    id: 3,
    creator: 'Tom Fisk',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/tom2.jpg'),
  },
  {
    id: 4,
    creator: 'Mikhail Nilov',
    type: 'video',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/video/mikhail.mp4'),
  },
  {
    id: 5,
    creator: 'Zhang Kaiyv',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/zhang1.jpg'),
  },
  {
    id: 6,
    creator: 'Zhang Kaiyv',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/zhang2.jpg'),
  },
  {
    id: 7,
    creator: 'Pixabay Henry',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/pixabay.jpg'),
  },
  {
    id: 8,
    creator: 'Pixabay Henry',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/pixabay2.jpg'),
  },
  {
    id: 9,
    creator: 'Shvets Gluhy',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/shvets.jpg'),
  },
  {
    id: 10,
    creator: 'Shvets Gluhy',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/shvets2.jpg'),
  },
  {
    id: 11,
    creator: 'Karolina Grabowska',
    type: 'video',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/video/karolina.mp4'),
  },
  {
    id: 12,
    creator: 'Pexels',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/pexels.jpg'),
  },
  {
    id: 13,
    creator: 'Pexels',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/pexels2.jpg'),
  },
  {
    id: 14,
    creator: 'Nida Polyn',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/nida.jpg'),
  },
  {
    id: 15,
    creator: 'Nida Polyn',
    type: 'photo',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/img/nida2.jpg'),
  },
  {
    id: 16,
    creator: 'Polina Tankilevitch',
    type: 'video',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/video/polina.mp4'),
  },
  {
    id: 17,
    creator: 'Peter San',
    type: 'video',
    profilePhoto: require('./data/img/profile.png'),
    src: require('./data/video/peter.mp4'),
  },
];

export default posts;
